### ISSUE TITLE
can i fine tune your inpaint model with my dataset?

### ISSUE THREAD

**Issue by hosnasn1987** [mikonvergence/ControlNetInpaint#19]
please tell me if i could fine tune your model with our dataset and give our objects a special prompt?

**Comment by mikonvergence** [comment]
In general - yes.

This pipeline consists of two major components - StableDiffusion Inpainting core and a ControlNet expansion. Each of those can be fine-tuned.

Whether fine-tuning should be applied to both models or just one of them will depend on the exact task you want to perform.

I want to note that this repository is not designed for fine-tuning, so we *might* consider incorporating a script if it's provided by someone else from the community - otherwise this is purely inference-oriented.

**Comment by hosnasn1987** [comment]
Hi Mikonvergence

Thank you for your reply

I have a assigned task in taht we should give a picture and masked picture
to a model and replace masked area with our desired object. we should
define this objects ourself. i tried dreambooth and lora for defining
objects, but they cant inpaint the masked area and correctly replace the
object. can you guide me to define my objects for controlnet inpaint or
stable diffusion inpainting models?

I will be very greateful

**Comment by mikonvergence** [comment]
The inpainting functionality of stable diffusion is fairly common, this should be a good start:

https://huggingface.co/runwayml/stable-diffusion-inpainting

The tool in this repository, ControlNetInpaint, is designed to do this with additional constraints defined by the various control signals - but this is not necessarily appropriate for some applications.
