### ISSUE TITLE
Can this work with SD 2 Inpainting 

### ISSUE THREAD

**Issue by aseemkhanduja** [mikonvergence/ControlNetInpaint#2]
Thanks a ton for this repo. I have 2 questions: 
1. Is there a way to make it work with Sd 2 Inpainting and potentially upcoming inpainting models ( XL etc)
2. If I have a ckpt of an custom inpainting model, how can I convert that to diffusers format?

**Comment by mikonvergence** [comment]
Hello! Thank you.
1. Yes, but this would require training a new ControlNet model. This repository builds on top of existing pre-trained models. If new models for SD2 or XL are released and available via diffusers, I will likely incorporate them too.
2. This is more of a question about diffusers, so I suggest checking the documentation on that.

**Comment by aseemkhanduja** [comment]
Great, Thanks a lot @mikonvergence. Since SD2 Inpainting is already available, do you plan to add that soon?

**Comment by mikonvergence** [comment]
This pipeline requires 2 elements:
i. an inpainting model (such as SD2)
ii. a ControlNet trained for that inpainting model

I am not aware of widely-used weights for a SD2 version of ControlNet (I've seen some models published on HF but haven't tested them). It should also be compatible with `diffusers.ControlNetModel` (https://huggingface.co/docs/diffusers/main/en/api/models#diffusers.ControlNetModel) since the pipeline is built specifically for diffusers.

Can you point to any examples of using diffusers for ControlNet with SD2 and corresponding ControlNet weights? If I missed something and it is already supported, I am happy to incorporate it into this project within the next few weeks!
