### ISSUE TITLE
About 'strength' Parameter in StableDiffusionControlNetInpaintPipeline Compared to StableDiffusionInpaintPipeline

### ISSUE THREAD

**Issue by swim2sun** [mikonvergence/ControlNetInpaint#20]
The `StableDiffusionInpaintPipeline` introduces a `strength` parameter, as detailed in the documentation [here](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/inpaint#diffusers.StableDiffusionInpaintPipeline.__call__.strength). However, I couldn't locate this parameter in the `StableDiffusionControlNetInpaintPipeline`.

If I use the parameters `num_inference_steps=40` and `strength=0.93` in `StableDiffusionInpaintPipeline`, should I then use `num_inference_steps=37` (calculated as 40 * 0.93) in `StableDiffusionControlNetInpaintPipeline`?

**Comment by mikonvergence** [comment]
Hi, `StableDiffusionControlNetInpaintPipeline` was designed to inherit all parameters from `StableDiffusionInpaintPipeline` but was written in March 2023, which means that some part of the interface has changed over time.

The `strength` has been added to the interface in May 2023 in commit [c09c4f3](https://github.com/huggingface/diffusers/commit/c09c4f3ab7ab7d46727949e003facb391e1e8b8d).

There is no way to control this in this version without changing the underlying code - since the process always starts with a sample of pure noise (which is the same as a constant strength of 1.0).

If this is a crucial functionality for you, we can consider a PR for this. Let me know what you think.

**Comment by swim2sun** [comment]
Hi, @mikonvergence  thank you for your clarification. 

I tried to reference your code and make modifications based on the latest version of `diffusers`. However, I noticed that `StableDiffusionControlNetInpaintPipeline` inherits from `StableDiffusionControlNetPipeline`, and the latest version of `StableDiffusionControlNetPipeline` also does not include the `strength` parameter. As I'm still in the early stages of using stable diffusion and not familiar with the details, I find it challenging to proceed without this information.

I appreciate the information you provided. I will attempt to use `StableDiffusionControlNetInpaintPipeline` and compare the effects between `strength=1` and `strength=0.93`. 

Thank you for your work on this repo, it's fantastic!
